import { formatCurrency } from "@/lib/format";
import type { AuditRecord, Customer, Payment, StoredCase } from "@/lib/models";

const T = {
  t1: "2026-01-12T09:00:00.000Z",
  t2: "2026-02-03T11:30:00.000Z",
  t3: "2026-03-18T08:15:00.000Z",
  t4: "2026-04-09T14:45:00.000Z",
  t5: "2026-05-21T10:00:00.000Z",
  t6: "2026-06-02T16:20:00.000Z",
  t7: "2026-06-14T09:40:00.000Z",
  t8: "2026-07-01T12:00:00.000Z",
  t9: "2026-07-22T13:10:00.000Z",
  t10: "2026-08-05T07:55:00.000Z",
} as const;

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: "CUS-001",
    name: "Acme Technologies",
    email: "billing@acme-technologies.example",
    status: "At risk",
    totalPaid: 12000,
    totalAtRisk: 0,
    totalRecovered: 0,
    createdAt: T.t1,
  },
  {
    id: "CUS-002",
    name: "Northstar Labs",
    email: "accounts@northstar-labs.example",
    status: "At risk",
    totalPaid: 8900,
    totalAtRisk: 0,
    totalRecovered: 0,
    createdAt: T.t2,
  },
  {
    id: "CUS-003",
    name: "Vertex Commerce",
    email: "finance@vertex-commerce.example",
    status: "At risk",
    totalPaid: 24500,
    totalAtRisk: 0,
    totalRecovered: 0,
    createdAt: T.t3,
  },
  {
    id: "CUS-004",
    name: "BluePeak Retail",
    email: "payments@bluepeak-retail.example",
    status: "At risk",
    totalPaid: 0,
    totalAtRisk: 0,
    totalRecovered: 0,
    createdAt: T.t4,
  },
  {
    id: "CUS-005",
    name: "Nova Systems",
    email: "ap@nova-systems.example",
    status: "Active",
    totalPaid: 15600,
    totalAtRisk: 0,
    totalRecovered: 0,
    createdAt: T.t5,
  },
];

export const SEED_PAYMENTS: Payment[] = [
  {
    id: "PAY-001",
    customerId: "CUS-001",
    amountValue: 12000,
    amount: formatCurrency(12000),
    status: "Paid",
    failureReason: "",
    attempts: 1,
    createdAt: T.t1,
    updatedAt: T.t1,
  },
  {
    id: "PAY-002",
    customerId: "CUS-001",
    amountValue: 42500,
    amount: formatCurrency(42500),
    status: "Failed",
    failureReason: "Temporary bank failure",
    attempts: 0,
    createdAt: T.t6,
    updatedAt: T.t6,
    recoveryCaseId: "REC-001",
  },
  {
    id: "PAY-003",
    customerId: "CUS-002",
    amountValue: 8900,
    amount: formatCurrency(8900),
    status: "Paid",
    failureReason: "",
    attempts: 1,
    createdAt: T.t2,
    updatedAt: T.t2,
  },
  {
    id: "PAY-004",
    customerId: "CUS-002",
    amountValue: 18900,
    amount: formatCurrency(18900),
    status: "Failed",
    failureReason: "Expired payment method",
    attempts: 1,
    createdAt: T.t7,
    updatedAt: T.t7,
    recoveryCaseId: "REC-002",
  },
  {
    id: "PAY-005",
    customerId: "CUS-002",
    amountValue: 45000,
    amount: formatCurrency(45000),
    status: "Blocked",
    failureReason: "Invalid payment method",
    attempts: 2,
    createdAt: T.t8,
    updatedAt: T.t9,
    recoveryCaseId: "REC-007",
  },
  {
    id: "PAY-006",
    customerId: "CUS-003",
    amountValue: 24500,
    amount: formatCurrency(24500),
    status: "Paid",
    failureReason: "",
    attempts: 1,
    createdAt: T.t3,
    updatedAt: T.t3,
  },
  {
    id: "PAY-007",
    customerId: "CUS-003",
    amountValue: 31200,
    amount: formatCurrency(31200),
    status: "Abandoned",
    failureReason: "High-intent abandonment",
    attempts: 0,
    createdAt: T.t8,
    updatedAt: T.t8,
    recoveryCaseId: "REC-003",
  },
  {
    id: "PAY-008",
    customerId: "CUS-004",
    amountValue: 75000,
    amount: formatCurrency(75000),
    status: "Overdue",
    failureReason: "Invoice overdue by 7 days",
    attempts: 0,
    createdAt: T.t9,
    updatedAt: T.t9,
    recoveryCaseId: "REC-004",
  },
  {
    id: "PAY-009",
    customerId: "CUS-005",
    amountValue: 15600,
    amount: formatCurrency(15600),
    status: "Paid",
    failureReason: "",
    attempts: 1,
    createdAt: T.t5,
    updatedAt: T.t5,
  },
  {
    id: "PAY-010",
    customerId: "CUS-005",
    amountValue: 7499,
    amount: formatCurrency(7499),
    status: "Failed",
    failureReason: "Insufficient funds",
    attempts: 2,
    createdAt: T.t10,
    updatedAt: T.t10,
    recoveryCaseId: "REC-005",
  },
  {
    id: "PAY-011",
    customerId: "CUS-001",
    amountValue: 3250,
    amount: formatCurrency(3250),
    status: "Recovered",
    failureReason: "Network timeout",
    attempts: 0,
    createdAt: T.t6,
    updatedAt: T.t8,
    recoveryCaseId: "REC-006",
  },
];

export const SEED_CASES: StoredCase[] = [
  {
    id: "REC-001",
    customerId: "CUS-001",
    customer: "Acme Technologies",
    paymentId: "PAY-002",
    type: "Payment failure",
    amount: formatCurrency(42500),
    amountValue: 42500,
    reason: "Temporary bank failure",
    confidence: 91,
    recoveryProbability: 88,
    rootCause: "Temporary payment processing issue",
    status: "Queued",
    recommendation: "Retry payment",
    description:
      "The payment appears to have failed due to a temporary bank-side issue.",
    attempts: 0,
    priority: "High",
    requiresApproval: false,
    executed: false,
    estimatedRecoveryAmount: 37400,
    createdAt: T.t6,
    updatedAt: T.t6,
  },
  {
    id: "REC-002",
    customerId: "CUS-002",
    customer: "Northstar Labs",
    paymentId: "PAY-004",
    type: "Failed subscription",
    amount: formatCurrency(18900),
    amountValue: 18900,
    reason: "Expired payment method",
    confidence: 94,
    recoveryProbability: 84,
    rootCause: "Expired or invalid payment method",
    status: "Queued",
    recommendation: "Request payment method update",
    description: "The customer's recurring payment method appears to be expired.",
    attempts: 1,
    priority: "High",
    requiresApproval: false,
    executed: false,
    estimatedRecoveryAmount: 15876,
    createdAt: T.t7,
    updatedAt: T.t7,
  },
  {
    id: "REC-003",
    customerId: "CUS-003",
    customer: "Vertex Commerce",
    paymentId: "PAY-007",
    type: "Checkout abandonment",
    amount: formatCurrency(31200),
    amountValue: 31200,
    reason: "High-intent abandonment",
    confidence: 87,
    recoveryProbability: 76,
    rootCause: "High-intent checkout abandonment",
    status: "Queued",
    recommendation: "Send payment-link recovery reminder",
    description: "The customer reached the final checkout stage and abandoned.",
    attempts: 0,
    priority: "High",
    requiresApproval: false,
    executed: false,
    estimatedRecoveryAmount: 23712,
    createdAt: T.t8,
    updatedAt: T.t8,
  },
  {
    id: "REC-004",
    customerId: "CUS-004",
    customer: "BluePeak Retail",
    paymentId: "PAY-008",
    type: "Overdue invoice",
    amount: formatCurrency(75000),
    amountValue: 75000,
    reason: "Invoice overdue by 7 days",
    confidence: 82,
    recoveryProbability: 68,
    rootCause: "Overdue invoice",
    status: "Needs approval",
    recommendation: "Send payment reminder",
    description: "High-value overdue invoice awaiting merchant approval.",
    attempts: 0,
    priority: "Critical",
    requiresApproval: true,
    executed: false,
    estimatedRecoveryAmount: 51000,
    createdAt: T.t9,
    updatedAt: T.t9,
  },
  {
    id: "REC-005",
    customerId: "CUS-005",
    customer: "Nova Systems",
    paymentId: "PAY-010",
    type: "Payment failure",
    amount: formatCurrency(7499),
    amountValue: 7499,
    reason: "Insufficient funds",
    confidence: 79,
    recoveryProbability: 44,
    rootCause: "Insufficient available funds",
    status: "Needs approval",
    recommendation: "Send payment link",
    description: "Retry limit reached; merchant approval is required.",
    attempts: 2,
    priority: "Low",
    requiresApproval: true,
    executed: false,
    estimatedRecoveryAmount: 3300,
    createdAt: T.t10,
    updatedAt: T.t10,
  },
  {
    id: "REC-006",
    customerId: "CUS-001",
    customer: "Acme Technologies",
    paymentId: "PAY-011",
    type: "Payment failure",
    amount: formatCurrency(3250),
    amountValue: 3250,
    reason: "Network timeout",
    confidence: 93,
    recoveryProbability: 88,
    rootCause: "Temporary payment processing issue",
    status: "High confidence",
    recommendation: "Retry payment",
    description: "The transaction timed out before a final payment state was received.",
    attempts: 0,
    priority: "High",
    requiresApproval: false,
    executed: true,
    executedAt: T.t8,
    estimatedRecoveryAmount: 2860,
    createdAt: T.t6,
    updatedAt: T.t8,
  },
  {
    id: "REC-007",
    customerId: "CUS-002",
    customer: "Northstar Labs",
    paymentId: "PAY-005",
    type: "Payment failure",
    amount: formatCurrency(45000),
    amountValue: 45000,
    reason: "Invalid payment method",
    confidence: 85,
    recoveryProbability: 66,
    rootCause: "Expired or invalid payment method",
    status: "Needs approval",
    recommendation: "Request payment method update",
    description: "Recovery was blocked by the merchant.",
    attempts: 2,
    priority: "High",
    requiresApproval: true,
    executed: false,
    blocked: true,
    estimatedRecoveryAmount: 29700,
    createdAt: T.t8,
    updatedAt: T.t9,
  },
];

export const SEED_AUDIT: AuditRecord[] = [
  {
    id: "AUD-S001",
    timestamp: T.t8,
    caseId: "REC-006",
    customer: "Acme Technologies",
    event: "Case analyzed",
    action: "Retry payment",
    confidence: 93,
    approvalStatus: "Auto-approved",
    amountValue: 2860,
    amount: formatCurrency(2860),
  },
  {
    id: "AUD-S002",
    timestamp: T.t8,
    caseId: "REC-006",
    customer: "Acme Technologies",
    event: "Root cause identified",
    action: "Retry payment",
    confidence: 93,
    approvalStatus: "Auto-approved",
    amountValue: 2860,
    amount: formatCurrency(2860),
  },
  {
    id: "AUD-S003",
    timestamp: T.t8,
    caseId: "REC-006",
    customer: "Acme Technologies",
    event: "Recovery action recommended",
    action: "Retry payment",
    confidence: 93,
    approvalStatus: "Auto-approved",
    amountValue: 2860,
    amount: formatCurrency(2860),
  },
  {
    id: "AUD-S004",
    timestamp: T.t8,
    caseId: "REC-006",
    customer: "Acme Technologies",
    event: "Auto-approval eligible",
    action: "Retry payment",
    confidence: 93,
    approvalStatus: "Auto-approved",
    amountValue: 2860,
    amount: formatCurrency(2860),
  },
  {
    id: "AUD-S005",
    timestamp: T.t8,
    caseId: "REC-006",
    customer: "Acme Technologies",
    event: "Recovery action executed",
    action: "Retry payment",
    confidence: 93,
    approvalStatus: "Auto-approved",
    amountValue: 2860,
    amount: formatCurrency(2860),
  },
  {
    id: "AUD-S006",
    timestamp: T.t9,
    caseId: "REC-004",
    customer: "BluePeak Retail",
    event: "Case analyzed",
    action: "Send payment reminder",
    confidence: 82,
    approvalStatus: "Approval required",
    amountValue: 51000,
    amount: formatCurrency(51000),
  },
  {
    id: "AUD-S007",
    timestamp: T.t9,
    caseId: "REC-004",
    customer: "BluePeak Retail",
    event: "Root cause identified",
    action: "Send payment reminder",
    confidence: 82,
    approvalStatus: "Approval required",
    amountValue: 51000,
    amount: formatCurrency(51000),
  },
  {
    id: "AUD-S008",
    timestamp: T.t9,
    caseId: "REC-004",
    customer: "BluePeak Retail",
    event: "Recovery action recommended",
    action: "Send payment reminder",
    confidence: 82,
    approvalStatus: "Approval required",
    amountValue: 51000,
    amount: formatCurrency(51000),
  },
  {
    id: "AUD-S009",
    timestamp: T.t9,
    caseId: "REC-004",
    customer: "BluePeak Retail",
    event: "Approval required",
    action: "Send payment reminder",
    confidence: 82,
    approvalStatus: "Approval required",
    amountValue: 51000,
    amount: formatCurrency(51000),
  },
  {
    id: "AUD-S010",
    timestamp: T.t9,
    caseId: "REC-007",
    customer: "Northstar Labs",
    event: "Case analyzed",
    action: "Request payment method update",
    confidence: 85,
    approvalStatus: "Blocked",
    amountValue: 29700,
    amount: formatCurrency(29700),
  },
  {
    id: "AUD-S011",
    timestamp: T.t9,
    caseId: "REC-007",
    customer: "Northstar Labs",
    event: "Root cause identified",
    action: "Request payment method update",
    confidence: 85,
    approvalStatus: "Blocked",
    amountValue: 29700,
    amount: formatCurrency(29700),
  },
  {
    id: "AUD-S012",
    timestamp: T.t9,
    caseId: "REC-007",
    customer: "Northstar Labs",
    event: "Recovery action recommended",
    action: "Request payment method update",
    confidence: 85,
    approvalStatus: "Blocked",
    amountValue: 29700,
    amount: formatCurrency(29700),
  },
  {
    id: "AUD-S013",
    timestamp: T.t9,
    caseId: "REC-007",
    customer: "Northstar Labs",
    event: "Approval required",
    action: "Request payment method update",
    confidence: 85,
    approvalStatus: "Blocked",
    amountValue: 29700,
    amount: formatCurrency(29700),
  },
  {
    id: "AUD-S014",
    timestamp: T.t9,
    caseId: "REC-007",
    customer: "Northstar Labs",
    event: "Recovery action blocked",
    action: "Request payment method update",
    confidence: 85,
    approvalStatus: "Blocked",
    amountValue: 29700,
    amount: formatCurrency(29700),
  },
];
